In [14]:
import tensorflow as tf

In [ ]:
sess=tf.InteractiveSession()

In [15]:
x=tf.constant([[1,9,2,7],[3,3,6,6],[7,6,5,3],[1,9,1,9]])

In [16]:
## using .eval() to change the tensor object to numpy array so as to show

In [17]:
x.eval()

array([[1, 9, 2, 7],
       [3, 3, 6, 6],
       [7, 6, 5, 3],
       [1, 9, 1, 9]])

#### shape

In [19]:
tf.shape(x).eval()

array([4, 4])

#### size

In [20]:
tf.size(x).eval()

16

#### rank

rank 有一点层级的意思。比如rank 1 可以用 t [i] 来选到那个数  rank 2 可以用 t [i,j] 来选到那个数

In [6]:
tf.rank(x).eval()

2

In [8]:
x[3,1].eval()    # 4th row 2nd number

9

#### reshape

In [8]:
tf.reshape(x,[8,2]).eval()

array([[1, 9],
       [2, 7],
       [3, 3],
       [6, 6],
       [7, 6],
       [5, 3],
       [1, 9],
       [1, 9]], dtype=int32)

#### squeeze

#### Remove 1d in the tensor

In [ ]:
x=tf.constant([[[1,9,2,7],[3,3,6,6],[7,6,5,3],[1,9,1,9]]])

In [19]:
tf.shape(x).eval()

array([1, 4, 4], dtype=int32)

In [15]:
x.eval()

array([[[1, 9, 2, 7],
        [3, 3, 6, 6],
        [7, 6, 5, 3],
        [1, 9, 1, 9]]], dtype=int32)

In [21]:
z=tf.squeeze(x).eval()

In [22]:
tf.shape(z).eval()

array([4, 4], dtype=int32)

#### Expand dimension

In [9]:
x=tf.constant([[[1,9,2,7],[3,3,6,6],[7,6,5,3]],[[1,9,2,7],
                                                          [3,3,6,6],[7,6,5,3]]])

In [10]:
tf.shape(x).eval()

array([2, 3, 4], dtype=int32)

In [20]:
z=tf.expand_dims(x,-2)

In [21]:
tf.shape(z).eval()

array([2, 3, 1, 4], dtype=int32)

In [22]:
z.eval()

array([[[[1, 9, 2, 7]],

        [[3, 3, 6, 6]],

        [[7, 6, 5, 3]]],


       [[[1, 9, 2, 7]],

        [[3, 3, 6, 6]],

        [[7, 6, 5, 3]]]], dtype=int32)

In [111]:
# 0  0th element expansion 2 to 1,2                   shape =[1,2,3,4]
# 1  1st element expansion 3 to 1,3                   shape =[2,1,3,4]
# 2  2nd element expansion 4 to 1,4                   shape =[2,3,1,4]
# 3  2nd element expansion 4 to 4,1                   shape =[2,3,4,1]
# -1 last element expansion 4 to 4,1                  shape =[2,3,4,1]
# -2 second last element expansion 3 to 3,1           shape =[2,3,1,4]
# -3 third last element expansion 2 to                shape =[2,1,3,4]
# -4 third last element expansion 2 to 1,2            shape =[1,2,3,4]