### How to create tensors?

In [1]:
## tf.constant
## use numpy array dtypes are pretty comparable

In [1]:
import tensorflow as tf
import numpy as np

In [2]:
a = np.array([[2,3],[1,2]], dtype= 'int32')

In [3]:
b = np.array([[1,0],[2,1]], dtype= 'int32')

In [5]:
sess=tf.InteractiveSession()

In [5]:
tf.add(a,b).eval()

array([[3, 3],
       [3, 3]])

### Matrix operations

In [6]:
## Reference:Building Machine Learning Projects with TensorFlow, Rodolfo Bonnin

In [7]:
sess=tf.InteractiveSession()

C:\Users\Administrator\Anaconda3\lib\site-packages\tensorflow\python\client\session.py:1714: UserWarning: An interactive session is already active. This can cause out-of-memory errors in some cases. You must explicitly call `InteractiveSession.close()` to release resources held by the other session(s).
  warnings.warn('An interactive session is already active. This can '


In [17]:
x=tf.constant([[1,2,3],[4,5,6]], dtype= 'float32')

In [18]:
y=tf.constant([[1,1,1],[5,7,5],[2,1,3]], dtype= 'float32')

#### Matrix Multiply

In [19]:
tf.matmul(x,y).eval()    # matrix multiply

array([[17., 18., 20.],
       [41., 45., 47.]], dtype=float32)

#### Inversion

In [15]:
tf.matrix_inverse(y).eval()  # only float could have inverse operation 

array([[ 8.00000191, -1.00000024, -1.        ],
       [-2.50000048,  0.50000006, -0.        ],
       [-4.50000048,  0.50000012,  1.        ]], dtype=float32)

#### transpose

In [7]:
tf.transpose(x).eval()  # matrix transpose

array([[1, 4],
       [2, 5],
       [3, 6]], dtype=int32)

#### determinant: 方阵的行列式

In [9]:
tf.matrix_determinant(y).eval() # matrix determinant

2.0

In [10]:
y.eval()

array([[1., 1., 1.],
       [5., 7., 5.],
       [2., 1., 3.]], dtype=float32)

In [12]:
m=tf.constant([[1,2],[3,4]],dtype='float32')
tf.matrix_determinant(m).eval()

-2.0

In [8]:
tf.matrix_determinant?

#### solve functions

In [13]:
tf.matrix_solve(y,[[10],[10],[10]]).eval()  # solve function x1 +5x2 + 2x3  =10

array([[ 60.00001 ],
       [-20.000004],
       [-30.000004]], dtype=float32)

#### Reductions

In [15]:
tf.reduce_prod?

In [21]:
x=tf.constant([[1,2,3],[4,5,6],[7,8,9]])

In [4]:
tf.reduce_prod(x).eval()

362880

In [10]:
#Computes the product of elements across dimensions of a tensor
tf.reduce_prod(x, reduction_indices=1).eval() 

array([  6, 120, 504], dtype=int32)

In [12]:
tf.reduce_max(x, reduction_indices=1).eval()

array([3, 6, 9], dtype=int32)

In [23]:
tf.reduce_min(x, reduction_indices=1).eval()

array([1, 4, 7], dtype=int32)

In [14]:
tf.reduce_mean(x, reduction_indices=1).eval()

array([2, 5, 8], dtype=int32)

#### About Boolean

In [16]:
x=tf.constant([[True,False,True],[True,True,True],[False,False,False]])

In [19]:
# compute logic and
tf.reduce_all(x,reduction_indices=1).eval()

array([False,  True, False], dtype=bool)

In [20]:
tf.reduce_any(x,reduction_indices=1).eval()

array([ True,  True, False], dtype=bool)