In [1]:
import tensorflow as tf

In [4]:
sess=tf.InteractiveSession()

#### matrix slicing

In [7]:
matrix=tf.constant([[1,2,3],[4,5,6],[7,8,9]])
matrix.eval()

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [6]:
# start from [0,1], shape of [3,2]
tf.slice(matrix,[0,1],[3,2]).eval()

array([[2, 3],
       [5, 6],
       [8, 9]])

#### array spliting

In [10]:
array_1=tf.constant([1,2,3,4,5,6,7,8])  # this is a rank 1 tensor

In [22]:
array_1.eval()

array([1, 2, 3, 4, 5, 6, 7, 8])

In [29]:
z=tf.split(array_1,[2,6],0)      # value, size, axis,分成有2列的和6列的

In [17]:
z[0].eval()

array([1, 2])

In [7]:
z[1].eval()

array([3, 4, 5, 6, 7, 8], dtype=int32)

#### matrix spliting

In [26]:
matrix.eval()

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [27]:
tf.split?

In [23]:
y=tf.split(matrix,[2,1],0)

In [24]:
y[0].eval()

array([[1, 2, 3],
       [4, 5, 6]])

In [25]:
y[1].eval()

array([[7, 8, 9]])

#### padding

In [39]:
matrix.eval()

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [30]:
tf.pad(matrix,[[0,0],[2,2]]).eval()  #上下没有 左右各两个

array([[0, 0, 1, 2, 3, 0, 0],
       [0, 0, 4, 5, 6, 0, 0],
       [0, 0, 7, 8, 9, 0, 0]])

In [36]:
tf.pad?

In [38]:
tf.pad(matrix,[[1,1],[2,2]],"SYMMETRIC").eval() #把边缘（也就是对称轴）也复制了，从对称轴开始复制

array([[2, 1, 1, 2, 3, 3, 2],
       [2, 1, 1, 2, 3, 3, 2],
       [5, 4, 4, 5, 6, 6, 5],
       [8, 7, 7, 8, 9, 9, 8],
       [8, 7, 7, 8, 9, 9, 8]])

In [40]:
tf.pad(matrix,[[0,0],[2,2]],"REFLECT").eval() #定好边缘（可理解为对称轴），按边缘翻(边缘不复制)

array([[3, 2, 1, 2, 3, 2, 1],
       [6, 5, 4, 5, 6, 5, 4],
       [9, 8, 7, 8, 9, 8, 7]])

#### concat

In [49]:
tf.concat? #tf.concat(values, axis, name='concat')

In [32]:
matrix_2=tf.constant([[3],[3],[3]])

In [33]:
tf.rank(matrix_2).eval()

2

In [34]:
tf.rank(matrix).eval()

2

In [24]:
tf.concat([matrix,matrix_2],1).eval()

array([[1, 2, 3, 3],
       [4, 5, 6, 3],
       [7, 8, 9, 3]], dtype=int32)

In [25]:
#shape must be rank 2 but receive rank 1 