In [1]:
import tensorflow as tf

In [2]:
sess= tf.InteractiveSession()

#### arg_max, arg_min

In [3]:
x=tf.constant([[1,2,3,4],[2,5,3,4],[3,2,1,4],[4,2,3,4]])

In [5]:
tf.argmax(x,1).eval() #最大值的位置

array([3, 1, 3, 0], dtype=int64)

In [6]:
tf.argmin(x,1).eval()

array([0, 0, 2, 1], dtype=int64)

#### unique

In [7]:
x=tf.constant([1,2,3,4,2,5,5])

In [14]:
m,h=tf.unique(x)
m.eval(),h.eval()

(array([1, 2, 3, 4, 5]), array([0, 1, 2, 3, 1, 4, 4]))

In [12]:
tf.unique?

In [8]:
tf.unique(x)[0].eval()   # give the unique value

array([1, 2, 3, 4, 5])

In [9]:
tf.unique(x)[1].eval()   # gives the unique group names

array([0, 1, 2, 3, 1, 4, 4])

#### boolean

In [15]:
x= tf.constant([[True,False],[False,False],[True,False],[False,True]])

In [16]:
tf.where(x).eval() #show true values

array([[0, 0],
       [2, 0],
       [3, 1]], dtype=int64)